# Generated by Django 4.1.6 on 2023-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='post',
            field=models.ImageField(default='kar', upload_to='posters'),
            preserve_default=False,
        ),
    ]
